import type { CurrentUser } from '@/types/app';

export const mockCurrentUser: CurrentUser = {
  id: 'user-admin',
  username: 'admin',
  nickname: '系统管理员',
  deptName: '信息中心',
  roleCodes: ['super_admin'],
  dataScope: 'all',
  permissions: [
    '*:*:*',
    'knowledge:qa:use',
    'knowledge:conversation:update',
    'knowledge:base:view',
    'knowledge:base:create',
    'knowledge:base:update',
    'knowledge:base:delete',
    'knowledge:document:view',
    'knowledge:document:create',
    'knowledge:document:update',
    'knowledge:document:delete',
    'system:user:view',
    'system:user:create',
    'system:user:update',
    'system:user:delete',
    'system:dept:view',
    'system:dept:create',
    'system:dept:update',
    'system:dept:delete',
    'system:post:view',
    'system:post:create',
    'system:post:update',
    'system:post:delete',
    'system:role:view',
    'system:role:create',
    'system:role:update',
    'system:role:delete',
    'system:menu:view',
    'system:menu:create',
    'system:menu:update',
    'system:menu:delete',
    'system:log:login:view',
    'system:log:operation:view',
    'system:setting:view',
    'system:setting:update',
  ],
};
